import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

/**
 * Capture a DOM element and produce a one-page PDF.
 * Used to export charts and pivot tables for sharing / pasting into reports.
 *
 * Layout: A4 landscape with title + body + timestamp footer.
 * Multi-page support and embedded multi-chart PDFs land in Sprint 2.5.
 */
export async function exportToPdf(opts: {
  element: HTMLElement;
  filename: string;
  title?: string;
}): Promise<void> {
  // Render the element to a high-DPI canvas
  const canvas = await html2canvas(opts.element, {
    scale: 2, // 2x for retina-quality PDF output
    useCORS: true,
    backgroundColor: '#ffffff',
    logging: false,
  });

  const imgWidth = canvas.width;
  const imgHeight = canvas.height;
  const dataUrl = canvas.toDataURL('image/png');

  // A4 landscape — 297mm × 210mm. Leave 15mm margins.
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 15;

  // Header — title left, generated-by right
  let cursorY = margin;
  if (opts.title) {
    pdf.setFontSize(16);
    pdf.setTextColor(15, 23, 42); // slate-900
    pdf.text(opts.title, margin, cursorY + 5);
    cursorY += 10;
  }
  pdf.setFontSize(9);
  pdf.setTextColor(100, 116, 139); // slate-500
  pdf.text('Generated by DataLens BI', pageW - margin, margin + 5, { align: 'right' });

  // Body — chart image, fit to remaining space preserving aspect
  const bodyTop = cursorY + 4;
  const footerH = 10;
  const bodyMaxW = pageW - 2 * margin;
  const bodyMaxH = pageH - bodyTop - footerH - margin;
  const aspect = imgWidth / imgHeight;
  let drawW = bodyMaxW;
  let drawH = drawW / aspect;
  if (drawH > bodyMaxH) {
    drawH = bodyMaxH;
    drawW = drawH * aspect;
  }
  const drawX = margin + (bodyMaxW - drawW) / 2;
  pdf.addImage(dataUrl, 'PNG', drawX, bodyTop, drawW, drawH);

  // Footer — timestamp
  pdf.setFontSize(8);
  pdf.setTextColor(148, 163, 184); // slate-400
  const stamp = new Date().toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
  pdf.text(stamp, margin, pageH - margin);

  const safeName = opts.filename.replace(/[^a-zA-Z0-9._-]/g, '_');
  pdf.save(safeName.endsWith('.pdf') ? safeName : `${safeName}.pdf`);
}
